name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next App
        run: npm run build && npm run export && touch ./out/.nojekyll
        env:
          HTTPS: 'true'
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_HOST_URL: ${{ secrets.REACT_APP_HOST_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out
